#!/usr/bin/env bash
# Install nginx on my web01 server
# Nginx should be listening on port 80
# When sent a GET request at root, return a page that contains at least
# one string "Holberton School"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!"  > /var/www/html/index.nginx-debian.html
sudo service nginx start
