#!/usr/bin/env bash

# Update package lists
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx
sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        return 200 "Hello World!\n";
    }
}
EOF

# Restart Nginx
sudo service nginx restart
