#!/usr/bin/env bash
# This script displays "bad luck" on 4th loop.
# "good luck" on 8th loop
# "Best School" on every other line

counter=1
while [ $counter -le 10 ]; do
	if [ $counter -eq 4 ]
	then
		echo bad luck
	elif [ $counter -eq 8 ]
	then
		echo good luck
	else
		echo Best School
	fi
	counter=$(( counter + 1 ))
done
