#!/usr/bin/env bash

# Set the key name and passphrase
KEY_NAME="school"
KEY_PASSPHRASE="betty"

# Generate the RSA key pair with 4096 bits and passphrase
ssh-keygen -t rsa -b 4096 -f $KEY_NAME -N "$KEY_PASSPHRASE"
